/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface NoteResponseDto {
  id: number;
  title: string;
  description: string;
  url: string;
  createdAt: string;
  updatedAt: string;
}
