/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { faker } from '@faker-js/faker';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';
import { useMutation, useQuery } from '@tanstack/react-query';
import { delay, http, HttpResponse } from 'msw';

import type { GetNotesListParams, NoteCreateRequestDto, NoteUpdateRequestDto, ServiceLoginRequestDto } from './dto';
import type { NoteResponseDto, NotesPageResponseDto, UserDataResponseDto, UserIdResponseDto } from './dto';
import { restApiAxiosClient } from './restApiAxiosClient';
/**
 * Возвращает список заметок с поддержкой текстового (BM25) или гибридного поиска (BM25 + семантический)
 * @summary Получить список заметок с пагинацией
 */
export const getNotesList = (params?: GetNotesListParams, signal?: AbortSignal) =>
  restApiAxiosClient<NotesPageResponseDto>({ url: `/notes`, method: 'GET', params, signal });

export const getGetNotesListQueryKey = (params?: GetNotesListParams) =>
  [`/notes`, ...(params ? [params] : [])] as const;

export const getGetNotesListQueryOptions = <TData = Awaited<ReturnType<typeof getNotesList>>, TError = unknown>(
  params?: GetNotesListParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotesList>>, TError, TData>> }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetNotesListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getNotesList>>> = ({ signal }) => getNotesList(params, signal);

  return { queryFn, queryKey, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getNotesList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetNotesListQueryResult = NonNullable<Awaited<ReturnType<typeof getNotesList>>>;
export type GetNotesListQueryError = unknown;

export function useGetNotesList<TData = Awaited<ReturnType<typeof getNotesList>>, TError = unknown>(
  params: undefined | GetNotesListParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotesList>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotesList>>,
          TError,
          Awaited<ReturnType<typeof getNotesList>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetNotesList<TData = Awaited<ReturnType<typeof getNotesList>>, TError = unknown>(
  params?: GetNotesListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotesList>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotesList>>,
          TError,
          Awaited<ReturnType<typeof getNotesList>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetNotesList<TData = Awaited<ReturnType<typeof getNotesList>>, TError = unknown>(
  params?: GetNotesListParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotesList>>, TError, TData>> },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Получить список заметок с пагинацией
 */

export function useGetNotesList<TData = Awaited<ReturnType<typeof getNotesList>>, TError = unknown>(
  params?: GetNotesListParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotesList>>, TError, TData>> },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetNotesListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Создает новую заметку с обязательным заголовком
 * @summary Создать новую заметку
 */
export const createNote = (noteCreateRequestDto: NoteCreateRequestDto, signal?: AbortSignal) =>
  restApiAxiosClient<NoteResponseDto>({
    url: `/notes`,
    headers: {'Content-Type': 'application/json', },
      method: 'POST',
    data: noteCreateRequestDto,
    signal
  });

export const getCreateNoteMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createNote>>,
    TError,
    { data: NoteCreateRequestDto },
    TContext
  >;
}): UseMutationOptions<Awaited<ReturnType<typeof createNote>>, TError, { data: NoteCreateRequestDto }, TContext> => {
  const mutationKey = ['createNote'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof createNote>>, { data: NoteCreateRequestDto }> = (
    props
  ) => {
    const { data } = props ?? {};

    return createNote(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateNoteMutationResult = NonNullable<Awaited<ReturnType<typeof createNote>>>;
export type CreateNoteMutationBody = NoteCreateRequestDto;
export type CreateNoteMutationError = unknown;

/**
 * @summary Создать новую заметку
 */
export const useCreateNote = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createNote>>,
      TError,
      { data: NoteCreateRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof createNote>>, TError, { data: NoteCreateRequestDto }, TContext> => {
  const mutationOptions = getCreateNoteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Проверяет секретный заголовок и на его основе регистрирует или возвращает данные пользователя
 * @summary Сервисный вход пользователя
 */
export const serviceLogin = (serviceLoginRequestDto: ServiceLoginRequestDto, signal?: AbortSignal) =>
  restApiAxiosClient<UserIdResponseDto>({
    url: `/auth/login`,
    headers: {'Content-Type': 'application/json', },
      method: 'POST',
    data: serviceLoginRequestDto,
    signal
  });

export const getServiceLoginMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof serviceLogin>>,
    TError,
    { data: ServiceLoginRequestDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof serviceLogin>>,
  TError,
  { data: ServiceLoginRequestDto },
  TContext
> => {
  const mutationKey = ['serviceLogin'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof serviceLogin>>, { data: ServiceLoginRequestDto }> = (
    props
  ) => {
    const { data } = props ?? {};

    return serviceLogin(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ServiceLoginMutationResult = NonNullable<Awaited<ReturnType<typeof serviceLogin>>>;
export type ServiceLoginMutationBody = ServiceLoginRequestDto;
export type ServiceLoginMutationError = unknown;

/**
 * @summary Сервисный вход пользователя
 */
export const useServiceLogin = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof serviceLogin>>,
      TError,
      { data: ServiceLoginRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof serviceLogin>>, TError, { data: ServiceLoginRequestDto }, TContext> => {
  const mutationOptions = getServiceLoginMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Помечает заметку как удаленную (isDeleted = true)
 * @summary Удалить заметку (мягкое удаление)
 */
export const deleteNote = (id: number) => restApiAxiosClient<null>({ url: `/notes/${id}`, method: 'DELETE' });

export const getDeleteNoteMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteNote>>, TError, { id: number }, TContext>;
}): UseMutationOptions<Awaited<ReturnType<typeof deleteNote>>, TError, { id: number }, TContext> => {
  const mutationKey = ['deleteNote'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteNote>>, { id: number }> = (props) => {
    const { id } = props ?? {};

    return deleteNote(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteNoteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteNote>>>;

export type DeleteNoteMutationError = unknown;

/**
 * @summary Удалить заметку (мягкое удаление)
 */
export const useDeleteNote = <TError = unknown, TContext = unknown>(
  options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteNote>>, TError, { id: number }, TContext> },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof deleteNote>>, TError, { id: number }, TContext> => {
  const mutationOptions = getDeleteNoteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Обновляет поля заметки (partial update)
 * @summary Обновить заметку
 */
export const updateNote = (id: number, noteUpdateRequestDto: NoteUpdateRequestDto) =>
  restApiAxiosClient<NoteResponseDto>({
    url: `/notes/${id}`,
    headers: {'Content-Type': 'application/json', },
      method: 'PATCH',
    data: noteUpdateRequestDto
  });

export const getUpdateNoteMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateNote>>,
    TError,
    { id: number; data: NoteUpdateRequestDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateNote>>,
  TError,
  { id: number; data: NoteUpdateRequestDto },
  TContext
> => {
  const mutationKey = ['updateNote'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateNote>>,
    { id: number; data: NoteUpdateRequestDto }
  > = (props) => {
    const { data, id } = props ?? {};

    return updateNote(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateNoteMutationResult = NonNullable<Awaited<ReturnType<typeof updateNote>>>;
export type UpdateNoteMutationBody = NoteUpdateRequestDto;
export type UpdateNoteMutationError = unknown;

/**
 * @summary Обновить заметку
 */
export const useUpdateNote = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateNote>>,
      TError,
      { id: number; data: NoteUpdateRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateNote>>,
  TError,
  { id: number; data: NoteUpdateRequestDto },
  TContext
> => {
  const mutationOptions = getUpdateNoteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * Возвращает информацию о текущем авторизованном пользователе
 * @summary Получить данные профиля пользователя
 */
export const getCurrentUser = (signal?: AbortSignal) =>
  restApiAxiosClient<UserDataResponseDto>({ url: `/user/me`, method: 'GET', signal });

export const getGetCurrentUserQueryKey = () => [`/user/me`] as const;

export const getGetCurrentUserQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = unknown
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCurrentUserQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUser>>> = ({ signal }) => getCurrentUser(signal);

  return { queryFn, queryKey, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentUser>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCurrentUserQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentUser>>>;
export type GetCurrentUserQueryError = unknown;

export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = unknown>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUser>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUser>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUser>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUser>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = unknown>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>> },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Получить данные профиля пользователя
 */

export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = unknown>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>> },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCurrentUserQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetNotesListResponseMock = (
  overrideResponse: Partial<NotesPageResponseDto> = {}
): NotesPageResponseDto => ({
  content: Array.from({ length: faker.number.int({ max: 10, min: 1 }) }, (_, i) => i + 1).map(() => ({
    id: faker.number.int({ max: undefined, min: undefined, multipleOf: undefined }),
    description: faker.string.alpha({ length: { min: 10, max: 20 } }),
    title: faker.string.alpha({ length: { min: 10, max: 20 } }),
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    url: faker.string.alpha({ length: { min: 10, max: 20 } }),
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`
  })),
  page: faker.number.int({ max: undefined, min: undefined, multipleOf: undefined }),
  size: faker.number.int({ max: undefined, min: undefined, multipleOf: undefined }),
  totalElements: faker.number.int({ max: undefined, min: undefined, multipleOf: undefined }),
  isLast: faker.datatype.boolean(),
  totalPages: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
  ...overrideResponse
});

export const getCreateNoteResponseMock = (overrideResponse: Partial<NoteResponseDto> = {}): NoteResponseDto => ({
  id: faker.number.int({ max: undefined, min: undefined, multipleOf: undefined }),
  description: faker.string.alpha({ length: { min: 10, max: 20 } }),
  title: faker.string.alpha({ length: { min: 10, max: 20 } }),
  createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
  url: faker.string.alpha({ length: { min: 10, max: 20 } }),
  updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
  ...overrideResponse
});

export const getServiceLoginResponseMock = (overrideResponse: Partial<UserIdResponseDto> = {}): UserIdResponseDto => ({
  userId: faker.number.int({ max: undefined, min: undefined, multipleOf: undefined }),
  ...overrideResponse
});

export const getUpdateNoteResponseMock = (overrideResponse: Partial<NoteResponseDto> = {}): NoteResponseDto => ({
  id: faker.number.int({ max: undefined, min: undefined, multipleOf: undefined }),
  description: faker.string.alpha({ length: { min: 10, max: 20 } }),
  title: faker.string.alpha({ length: { min: 10, max: 20 } }),
  createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
  url: faker.string.alpha({ length: { min: 10, max: 20 } }),
  updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
  ...overrideResponse
});

export const getGetCurrentUserResponseMock = (
  overrideResponse: Partial<UserDataResponseDto> = {}
): UserDataResponseDto => ({
  userId: faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
  userName: faker.string.alpha({ length: { min: 10, max: 20 } }),
  ...overrideResponse
});

export const getGetNotesListMockHandler = (
  overrideResponse?:
    | NotesPageResponseDto
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<NotesPageResponseDto> | NotesPageResponseDto)
) =>
  http.get('*/notes', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse === undefined
    ? getGetNotesListResponseMock()
    : (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)),
      { headers: { 'Content-Type': 'application/json' },
        status: 200
      })
  });

export const getCreateNoteMockHandler = (
  overrideResponse?:
    | NoteResponseDto
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<NoteResponseDto> | NoteResponseDto)
) =>
  http.post('*/notes', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse === undefined
    ? getCreateNoteResponseMock()
    : (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)),
      { headers: { 'Content-Type': 'application/json' },
        status: 200
      })
  });

export const getServiceLoginMockHandler = (
  overrideResponse?:
    | UserIdResponseDto
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<UserIdResponseDto> | UserIdResponseDto)
) =>
  http.post('*/auth/login', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse === undefined
    ? getServiceLoginResponseMock()
    : (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)),
      { headers: { 'Content-Type': 'application/json' },
        status: 200
      }
    );
  });

export const getDeleteNoteMockHandler = (
  overrideResponse?: null | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<null> | null)
) =>
  http.delete('*/notes/:id', async (info) => {
    await delay(1000);
    if (typeof overrideResponse === 'function') {
      await overrideResponse(info);
    }
    return new HttpResponse(null, { status: 200 });
  });

export const getUpdateNoteMockHandler = (
  overrideResponse?:
    | NoteResponseDto
    | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<NoteResponseDto> | NoteResponseDto)
) =>
  http.patch('*/notes/:id', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse === undefined
    ? getUpdateNoteResponseMock()
    : (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)),
      { headers: { 'Content-Type': 'application/json' },
        status: 200
      })
  });

export const getGetCurrentUserMockHandler = (
  overrideResponse?:
    | UserDataResponseDto
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<UserDataResponseDto> | UserDataResponseDto)
) =>
  http.get('*/user/me', async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse === undefined
    ? getGetCurrentUserResponseMock()
    : (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)),
      { headers: { 'Content-Type': 'application/json' },
        status: 200
      })
  });
export const getOpenAPIDefinitionMock = () => [
  getGetNotesListMockHandler(),
  getCreateNoteMockHandler(),
  getServiceLoginMockHandler(),
  getDeleteNoteMockHandler(),
  getUpdateNoteMockHandler(),
  getGetCurrentUserMockHandler()
];
