name: scms_backend_infrastructure

services:
  postgres-scms:
    container_name: postgres-scms
    image: postgres:17
    restart: unless-stopped
    environment:
      APP_DB_USERNAME: ${APP_DB_USERNAME}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
      POSTGRES_PASSWORD: ${ADMIN_DB_PASSWORD}
      POSTGRES_USER: ${ADMIN_DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ADMIN_DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - scms-network

  pgadmin-scms:
    container_name: pgadmin-scms
    image: dpage/pgadmin4
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PG_ADMIN_PORT}:80
    logging:
      driver: none
    networks:
      - scms-network

networks:
  scms-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
