# 0. Import .env
spring.config.import=optional:file:.env[.properties]

# 1. DB settings for application (app_user)
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${APP_DB_USERNAME}
spring.datasource.password=${APP_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. DB settings for Liquibase migrations (admin user)
spring.liquibase.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.liquibase.user=${ADMIN_DB_USERNAME}
spring.liquibase.password=${ADMIN_DB_PASSWORD}
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.parameters.db.app.user=${APP_DB_USERNAME}

# Application
server.port=${APP_PORT}
server.servlet.context-path=/api
springdoc.swagger-ui.path=/swagger

# JWT
jwt.secret=${AUTH_SECRET}

# next login auth secret
service.auth.login.secret=${SERVICE_AUTHORIZATION_SECRET}

# frontend allowed origins
app.cors.allowed-origins=${ALLOWED_ORIGINS}

# Actuator / Health Probes
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

# Spring AI Ollama Configuration
spring.ai.ollama.base-url=${OLLAMA_URL}
spring.ai.ollama.embedding.model=${OLLAMA_EMBEDDING_MODEL}
spring.ai.ollama.embedding.options.num-thread=4


